=== SWE-KARIM/java-soap-ws-course/Patient.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.kn.org/Patient"
        xmlns:tns="http://www.kn.org/Patient"
        elementFormDefault="qualified">

    <element name="patient" type="tns:Patient"/>
        <complexType name="Patient">
            <sequence>
                <element name="id" type="tns:ID" maxOccurs="1" />
                <element name="name" type="tns:Simple10Char" />
                <element name="phone " type="string" />
                <element name="age" type="int" />
                <element name="dob" type="date" />
                <element name="gender" type="tns:Gender" />
                <element name="email" type="string" maxOccurs="unbounded"/>
                <element name="payment" type="tns:PaymentType" />
            </sequence>
        </complexType>
        
        <complexType name="PaymentType">
			<choice>
				<element name="cash" type="int" />
				<element name="inshurance" type="tns:Inshurance" />
			</choice>
		</complexType>
		
		<complexType name="Inshurance">
			<all>
				<element name="provider" type="string" />
				<element name="limit" type="int" />
			</all>
		</complexType>
        
        <simpleType name="ID">
			<restriction base="int">
				<pattern value="[0-9]*"></pattern>
			</restriction>
		</simpleType>
		
		<simpleType name="Simple10Char">
			<restriction base="string">
				<maxLength value="10"></maxLength>
			</restriction>
		</simpleType>
		
		<simpleType name="Gender">
			<restriction base="string">
				<enumeration value="M"></enumeration>
				<enumeration value="F"></enumeration>
			</restriction>
		</simpleType>


</schema>

=== SWE-KARIM/java-soap-ws-course/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.kn.org/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kn.org/Patient Patient.xsd ">
	<tns:id>123</tns:id>
	<tns:name>tns:name</tns:name>
	<tns:phone>tns:phone</tns:phone>
	<tns:age>0</tns:age>
	<tns:dob>2001-01-01</tns:dob>
	<tns:gender>M</tns:gender>
	<tns:email>tns:email</tns:email>
	<tns:payment>
		<tns:inshurance>
			<tns:provider>Test Provider</tns:provider>
			<tns:limit>1000</tns:limit>
		</tns:inshurance>
	</tns:payment>
</tns:patient>
